# Generated by Django 4.1 on 2022-09-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('birth_day', models.DateField()),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
    ]
